# bash script to download sst files
# url http://www.esrl.noaa.gov/psd/data/gridded/data.noaa.oisst.v2.highres.html
# ftp base: ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.yyyy.v2.nc

SHELL = /bin/sh

all: sst.day.mean.2010.v2.nc sst.day.mean.2011.v2.nc sst.day.mean.2012.v2.nc sst.day.mean.2013.v2.nc sst.day.mean.2014.v2.nc

sst.day.mean.2010.v2.nc:
	curl -o sst.day.mean.2010.v2.nc 'ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.2010.v2.nc'
	
sst.day.mean.2011.v2.nc:
	curl -o sst.day.mean.2011.v2.nc 'ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.2011.v2.nc'
	
sst.day.mean.2012.v2.nc:
	curl -o sst.day.mean.2012.v2.nc 'ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.2012.v2.nc'

sst.day.mean.2013.v2.nc:
	curl -o sst.day.mean.2013.v2.nc 'ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.2013.v2.nc'

sst.day.mean.2014.v2.nc:
	curl -o sst.day.mean.2014.v2.nc 'ftp://ftp.cdc.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.2014.v2.nc'
